<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

genesis_structural_wrap( 'site-inner', 'close' );
genesis_markup( array(
	'close'   => '</div>',
	'context' => 'site-inner',
) );

do_action( 'genesis_before_footer' );
do_action( 'genesis_footer' );
do_action( 'genesis_after_footer' );

genesis_markup( array(
	'close'   => '</div>',
	'context' => 'site-container',
) );

do_action( 'genesis_after' );
wp_footer(); // We need this for plugins.

genesis_markup( array(
	'close'   => '</body>',
	'context' => 'body',
) );



?>

<?php if ( is_user_logged_in() ): 
        $terms_js = ''; 
	    $current_user = wp_get_current_user();  

	    //var_dump($current_user); exit(); 
		
		$tid = get_option("wny_selected_terms");
		$uid = $current_user->data->ID;


		global $wpdb;

		$results = $wpdb->get_results("SELECT *FROM wp_wny_user_terms WHERE 
		user_id = $uid  AND terms_id = $tid ");
 
		
		if(  count($results) == 0 ){
			include(WP_CONTENT_DIR."/plugins/wny_practitioners/templates/_terms.php");  
		}   
	
 ?>  
 <script > 
 jQuery(function(){   

	jQuery(".menu-item a span").each(function(){ 
		
		var url = jQuery(this).parent().attr('href');

        if( url.search('log-in') > 0){    
			jQuery(this).text('Logout');
			jQuery(this).parent().attr('href','/log-in/?action=logout'); 
		} 
	});

    
  }); 
</script>

<?php else: ?>  
<script > 
 jQuery(function(){   
 
    jQuery(".menu-item a span").each(function(){  
		var url = jQuery(this).parent().attr('href'); 
		if( url.search('account') > 0){    
			jQuery(this).parent().remove();
		} 
	});
 

	jQuery("#wpadminbar").css("display","none");  
    jQuery(".site-container .genesis-before-header").remove();  

    var html = '<div class="genesis-before-header" style="display:block;">'; 
    html += '<div class="hi-header"  ><p>Find a health practitioner near you today!</p></div></div>  '; 
    jQuery(".site-container").prepend(html);    
  });  



	
</script>

<?php endif; ?> 

</html>
